spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 3. Consul이 이 경로를 주기적으로 호출하여 건강 상태를 체크
        health-check-path: /actuator/health
        # 4. 헬스 체크 주기
        health-check-interval: 15s
        # 5. 서비스 ID를 고유하게 만들어 동일 호스트에서 여러 인스턴스 실행 가능
        instance-id: ${spring.application.name}:${random.value}