spring:
  datasource:
    url: jdbc:h2:mem:memberdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

member:
  greeting: "Hello, Dev Member!" # 개발 환경용 인사말
