server:
  port: 8888 # Config Server의 기본 포트

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/somefood/spring-cloud-study
          default-label: main
          search-paths: config-repo